"""rename_file_path_to_s3_key

Revision ID: 6bb503215d75
Revises: fd525cfeb13c
Create Date: 2025-04-24 03:21:24.563881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb503215d75'
down_revision: Union[str, None] = 'fd525cfeb13c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('s3_key', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('content_type', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('status', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('analysis', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_documents_s3_key'), 'documents', ['s3_key'], unique=True)
    op.drop_column('documents', 'description')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_documents_s3_key'), table_name='documents')
    op.alter_column('documents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('documents', 'analysis')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 's3_key')
    # ### end Alembic commands ###
